version: '3.8'

services:
  # Main Node.js application
  app:
    build: .
    ports:
      - "5001:5001"
    environment:
      - NODE_ENV=development
      - DATABASE_URL=${DATABASE_URL}
      - OPENAI_API_KEY=${OPENAI_API_KEY}
      - GOOGLE_AI_API_KEY=${GOOGLE_AI_API_KEY}
    depends_on:
      - ai-forecast
      - postgres
    volumes:
      - .:/app
      - /app/node_modules

  # AI Forecasting Service
  ai-forecast:
    build: ./ai_model
    ports:
      - "5002:5002"
    environment:
      - FLASK_ENV=development
      - PORT=5002
    volumes:
      - ./ai_model:/app
      - ai_models:/app/models

  # PostgreSQL Database
  postgres:
    image: postgres:15
    environment:
      - POSTGRES_DB=airsense
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data:
  ai_models: